// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proyecto_H.Data;

#nullable disable

namespace Proyecto_H.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20260505234539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_H.Dominio.Capacitacion", b =>
                {
                    b.Property<int>("IdCapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCapacitacion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TipoCapacitacionIdTipo")
                        .HasColumnType("integer");

                    b.HasKey("IdCapacitacion");

                    b.HasIndex("TipoCapacitacionIdTipo");

                    b.ToTable("Capacitacion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Certificado", b =>
                {
                    b.Property<int>("IdCertificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCertificado"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEvaluacion")
                        .HasColumnType("integer");

                    b.HasKey("IdCertificado");

                    b.HasIndex("IdEvaluacion")
                        .IsUnique();

                    b.ToTable("Certificado");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.DocenteCapacitacion", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdCapacitacion")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdCapacitacion");

                    b.HasIndex("IdCapacitacion");

                    b.ToTable("DocenteCapacitacion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.DocenteEspecialidad", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdEspecialidad");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("DocenteEspecialidad");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Evaluacion", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdInscripcion")
                        .HasColumnType("integer");

                    b.Property<decimal>("Nota")
                        .HasColumnType("numeric");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("IdInscripcion");

                    b.ToTable("Evaluacion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCapacitacion")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCapacitacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.PerfilAcademico", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("AñoFormacion")
                        .HasColumnType("integer");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NivelAcademico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("PerfilAcademico");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Rotacion", b =>
                {
                    b.Property<int>("IdRotacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRotacion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRotacion");

                    b.ToTable("Rotacion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.TipoCapacitacion", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTipo");

                    b.ToTable("TipoCapacitacion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.TutorAsignado", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .HasColumnType("integer");

                    b.Property<int>("IdDocente")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdEstudiante", "IdDocente");

                    b.HasIndex("IdDocente");

                    b.ToTable("TutorAsignado");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.UsuarioRotacion", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdRotacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUsuario", "IdRotacion");

                    b.HasIndex("IdRotacion");

                    b.ToTable("UsuarioRotacion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Capacitacion", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.TipoCapacitacion", null)
                        .WithMany("Capacitaciones")
                        .HasForeignKey("TipoCapacitacionIdTipo");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Certificado", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Evaluacion", "Evaluacion")
                        .WithOne("Certificado")
                        .HasForeignKey("Proyecto_H.Dominio.Certificado", "IdEvaluacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.DocenteCapacitacion", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Capacitacion", "Capacitacion")
                        .WithMany()
                        .HasForeignKey("IdCapacitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_H.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.DocenteEspecialidad", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Especialidad", "Especialidad")
                        .WithMany("DocenteEspecialidades")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_H.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Evaluacion", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("IdInscripcion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Inscripcion", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Capacitacion", "Capacitacion")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdCapacitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_H.Dominio.Usuario", "Usuario")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacitacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.PerfilAcademico", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.TutorAsignado", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Usuario", "Docente")
                        .WithMany()
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_H.Dominio.Usuario", "Estudiante")
                        .WithMany()
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.UsuarioRol", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_H.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.UsuarioRotacion", b =>
                {
                    b.HasOne("Proyecto_H.Dominio.Rotacion", "Rotacion")
                        .WithMany("UsuarioRotaciones")
                        .HasForeignKey("IdRotacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_H.Dominio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rotacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Capacitacion", b =>
                {
                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Especialidad", b =>
                {
                    b.Navigation("DocenteEspecialidades");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Evaluacion", b =>
                {
                    b.Navigation("Certificado");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Rotacion", b =>
                {
                    b.Navigation("UsuarioRotaciones");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.TipoCapacitacion", b =>
                {
                    b.Navigation("Capacitaciones");
                });

            modelBuilder.Entity("Proyecto_H.Dominio.Usuario", b =>
                {
                    b.Navigation("Inscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
